### ISSUE TITLE
socket.gaierror while running the "generate dockerfile" example 

### ISSUE THREAD

**Issue by athanell** [kaczmarj/neurodocker#115]
### Summary
When I run the example 
`run --rm kaczmarj/neurodocker:v0.3.1 generate -b ubuntu:16.04 -p apt --ants version=2.2.0`
I got into the socket.gaierror

Any ideas on what causes this error?
Thank you

### Platform details:
Ubuntu 16.04 ( inside VMbox )

###Error details 

```

sudo docker run --rm kaczmarj/neurodocker:v0.3.1 generate -b ubuntu:16.04 -p apt --ants version=2.2.0
Unable to find image 'kaczmarj/neurodocker:v0.3.1' locally
v0.3.1: Pulling from kaczmarj/neurodocker
88286f41530e: Pull complete 
cbf6c3c6bd80: Pull complete 
2592e13ad4e6: Pull complete 
Digest: sha256:d5acfc788c670f0d597e34e60d78fb93c276e2cd803a31b5ddbf225981c1ae83
Status: Downloaded newer image for kaczmarj/neurodocker:v0.3.1
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2dda72ccc0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dl.dropbox.com', port=443): Max retries exceeded with url: /s/2f4sui1z6lcgyek/ANTs-Linux-centos5_x86_64-v2.2.0-0740f91.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2dda72ccc0>: Failed to establish a new connection: [Errno -3] Try again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/neurodocker", line 11, in <module>
    load_entry_point('neurodocker', 'console_scripts', 'neurodocker')()
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 278, in main
    subparser_functions[namespace.subparser_name](namespace)
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 225, in generate
    df = Dockerfile(specs)
  File "/opt/neurodocker/neurodocker/generate.py", line 456, in __init__
    self.cmd = self._create_cmd()
  File "/opt/neurodocker/neurodocker/generate.py", line 477, in _create_cmd
    chunks = _get_dockerfile_chunks(self.specs)
  File "/opt/neurodocker/neurodocker/generate.py", line 435, in _get_dockerfile_chunks
    chunk = _get_dockerfile_chunk(instruction, options, specs)
  File "/opt/neurodocker/neurodocker/generate.py", line 413, in _get_dockerfile_chunk
    chunk = callable_(**options).cmd
  File "/opt/neurodocker/neurodocker/interfaces/ants.py", line 74, in __init__
    self.cmd = self._create_cmd()
  File "/opt/neurodocker/neurodocker/interfaces/ants.py", line 83, in _create_cmd
    chunks = [comment, self.install_binaries()]
  File "/opt/neurodocker/neurodocker/interfaces/ants.py", line 98, in install_binaries
    check_url(url)
  File "/opt/neurodocker/neurodocker/utils.py", line 141, in check_url
    request = requests.head(url, timeout=timeout, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 98, in head
    return request('head', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dl.dropbox.com', port=443): Max retries exceeded with url: /s/2f4sui1z6lcgyek/ANTs-Linux-centos5_x86_64-v2.2.0-0740f91.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2dda72ccc0>: Failed to establish a new connection: [Errno -3] Try again',))
```

**Comment by kaczmarj** [comment]
hi @athanell - are you connected to the internet while running this command? neurodocker will check that urls are reachable by default and will raise an error like the one you described if there is no internet connection. you can disable this check with the option `--no-check-urls` (see below). i will add some logic to display a more useful error message if there is no internet connection.

```
docker run --rm kaczmarj/neurodocker:v0.3.1 generate -b ubuntu:16.04 -p apt --ants version=2.2.0 --no-check-urls
```

**Comment by athanell** [comment]
Hello @kaczmarj , I believe that I had an active internet connection but I will redo the process when I am certain about the connection and I will keep you posted if the error persists

Thank you

**Comment by athanell** [comment]
Hello @kaczmarj ,
I do have an active Internet connection but I think that the problem is that I am behind a firewall. My docker is configured to run behind a proxy using guidelines I found in 
[https://stackoverflow.com/questions/26550360/docker-ubuntu-behind-proxy](url) and I can pull any image I want, though neurodocker does fail with the error mentioned above .
Running the example in a system that is not behind a firewall completed without any errors.

**Comment by kaczmarj** [comment]
Hi @athanell - thanks for the information. did you try with the `neurodocker generate` option `--no-check-urls`? if it fails with that option, there is a bug.

**Comment by athanell** [comment]
Hi @kaczmarj , 
Yes while running it with the option `--no-check-urls`, as you proposed there is no error and the dockerfile is created normally for my system which is behind a firewall. 

Thank you for your assistance
