### ISSUE TITLE
Can't save singularity recipe

### ISSUE THREAD

**Issue by yarikoptic** [kaczmarj/neurodocker#269]
```shell
$> docker run -it -v $PWD:$PWD --rm kaczmarj/neurodocker:master generate singularity --base debian:stretch -p apt --miniconda pip_install=torch,torchvision,xarray,netCDF4 create_env=preproc -o .datalad/environments/preproc/Singularity                    
# Generated by Neurodocker version 0.4.3-6-g12a2b6f
...
/neurodocker/startup.sh "$@"
Traceback (most recent call last):
  File "/usr/bin/neurodocker", line 11, in <module>
    load_entry_point('neurodocker', 'console_scripts', 'neurodocker')()
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 415, in main
    subparser_functions[namespace.subsubparser_name](namespace)
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 370, in generate
    recipe_obj.save(filepath=namespace.output)
AttributeError: 'SingularityRecipe' object has no attribute 'save'
```

**Comment by kaczmarj** [comment]
thanks @yarikoptic for the pointer. looks like a bug. i'll fix it soon
