### ISSUE TITLE
kwargs_from_env() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by yarikoptic** [kaczmarj/neurodocker#35]
decided to try a sample from README.md but didn't quite work out:
```shell
$> python sample.py
Traceback (most recent call last):
  File "sample.py", line 1, in <module>
    from neurodocker import Dockerfile, SpecsParser
  File "/home/yoh/proj/repronim/neurodocker/neurodocker/__init__.py", line 18, in <module>
    import neurodocker.docker
  File "/home/yoh/proj/repronim/neurodocker/neurodocker/docker/__init__.py", line 9, in <module>
    from neurodocker.docker.docker import client, DockerContainer, DockerImage
  File "/home/yoh/proj/repronim/neurodocker/neurodocker/docker/docker.py", line 33, in <module>
    client = docker.from_env(timeout=30)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 39, in from_env
    return Client.from_env(**kwargs)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 113, in from_env
    return cls(**kwargs_from_env(**kwargs))
TypeError: kwargs_from_env() got an unexpected keyword argument 'timeout'

$> cat sample.py
from neurodocker import Dockerfile, SpecsParser
from neurodocker.docker import DockerImage, DockerContainer

specs = {
    'base': 'ubuntu:17.04',
    'pkg_manager': 'apt',
    'check_urls': False,  # Verify communication with URLs used in build.
    'miniconda': {
        'python_version': '3.5.1',
        'conda_install': 'traits',
        'pip_install': 'https://github.com/nipy/nipype/archive/master.tar.gz'},
    'mrtrix3': {'use_binaries': False},
    'ants': {'version': '2.2.0', 'use_binaries': True},
    'fsl': {'version': '5.0.10', 'use_binaries': True},
    'spm': {'version': '12', 'matlab_version': 'R2017a'},
}

parser = SpecsParser(specs)
df = Dockerfile(parser.specs)
df.save('path/to/Dockerfile')
print(df)

```

**Comment by kaczmarj** [comment]
Sorry for the late reply — I'm currently abroad without consistent access to a computer. This looks like an issue with instantiating the Docker client. What version of the docker Python package do you have? Can you upgrade that package and try again?

'pip install -U docker'

I set the timeout because in some cases, I would get timeout errors when attempting to stop containers with the docker-Python API.

**Comment by kaczmarj** [comment]
Hi @yarikoptic - did you get this to work? I couldn't replicate this issue on my macOS machine with docker-py version 2.3.0.

**Comment by yarikoptic** [comment]
yeap -- that was it.  Thus please consider #37
